### 회원가입
POST http://localhost:8080/api/sign-up
Content-Type: application/json

{
    "username": "master",
    "email": "master@naver.com",
    "password": "1q2w3e4r!",
    "phoneNumber": "010-1234-5678",
    "role": "MASTER"
}

### 로그인
POST http://localhost:8080/api/sign-in
Content-Type: application/json

{
  "username": "owner",
  "password": "1q2w3e4r!"
}

### 공통 주문 상세 조회
GET http://localhost:8080/api/orders/5c161a0e-9242-442f-bac0-6ab27b3682e7
Authorization: {{MANAGER_TOKEN}}

### 공통 주문 목록 조회
GET http://localhost:8080/api/orders?username=manager&page=1&size=20&orderBy=latest
Authorization: {{OWNER_TOKEN}}

### 공통 주문 취소
POST http://localhost:8080/api/orders/3e50dce2-cd8d-42c5-aa59-725f69ec9c4f/cancel
Authorization: {{MANAGER_TOKEN}}

### 고객 주문 요청
POST http://localhost:8080/api/customer/orders
Authorization: {{CUSTOMER_TOKEN}}
Content-Type: application/json

{
  "shopId": "00000000-0000-0000-0000-000000000010",
  "address": "주소",
  "menuList": [
    {
      "menuId": "00000000-0000-0000-0000-000000000103",
      "quantity": 3
    }
  ]
}

### 점주 주문 수락
POST http://localhost:8080/api/owner/orders/8a780d74-7d86-4488-af2d-b6cadf595623/accept
Authorization: {{OWNER_TOKEN}}

### 점주 주문 상세 조회
GET http://localhost:8080/api/owner/orders/f7acd3ca-78a4-445e-a266-5428cb3fd314
Authorization: {{OWNER_TOKEN}}

### 점주 주문 목록 조회
GET http://localhost:8080/api/owner/orders?shopId=00000000-0000-0000-0000-000000000010&page=1&size=20&orderBy=latest
Authorization: {{OWNER_TOKEN}}

### 점주 주문 목록 조회(shop 검색 조건 x)
GET http://localhost:8080/api/owner/orders?page=1&size=20&orderBy=latest
Authorization: {{OWNER_TOKEN}}

### 점주 주문 접수
POST http://localhost:8080/api/owner/orders
Authorization: {{OWNER_TOKEN}}
Content-Type: application/json

{
  "shopId": "00000000-0000-0000-0000-000000000010",
  "address": "주소",
  "menuList": [
    {
      "menuId": "00000000-0000-0000-0000-000000000101",
      "quantity": 1
    },
    {
      "menuId": "00000000-0000-0000-0000-000000000102",
      "quantity": 2
    }
  ]
}

### 관리자 주문 생성
POST http://localhost:8080/api/manager/orders
Authorization: {{MANAGER_TOKEN}}
Content-Type: application/json

{
  "shopId": "00000000-0000-0000-0000-000000000010",
  "address": "주소",
  "menuList": [
    {
      "menuId": "00000000-0000-0000-0000-000000000101",
      "quantity": 1
    },
    {
      "menuId": "00000000-0000-0000-0000-000000000102",
      "quantity": 2
    }
  ],
  "orderStatus": "PENDING",
  "orderType": "OFFLINE"
}